apiVersion: v1
kind: Service
metadata:
  name: resume-website-service
spec:
  selector:
    app: resume-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
  type: NodePort