name: Docker Build and Push
on:
    push:
        branches:
            - master
    workflow_dispatch:
env:
    GOOD: Hello This is Output Variable
jobs:
    build:
        env: 
            NEW_VAR: This is new variable
        runs-on: ubuntu-latest
        steps:
            - name: Generate Output Variable
              run: echo "$GOOD"
            - name : checkout code
              uses: actions/checkout@v
            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Build and Push Docker Image
              uses: docker/build-push-action@v5
              with:
                    context: .
                    push: true
                    tags: ${{ secrets.DOCKER_USERNAME }}/resume-site:latest
    
    deploy:
        env: 
            NEW_VAR: This is new variable 
        needs: build
        runs-on: self-hosted
        steps:
            - name: Print New Variable
              run: echo "$NEW_VAR"
            - name: checkout code
              uses: actions/checkout@v6
            - name: Update K8s Deployment
              run: |
                  kubectl rollout restart deployment/resume-website-deployment
            - name: Verfy Deployment
              run: |
                  kubectl rollout status deployment/resume-website-deployment
    report:
      needs: [build,deploy]
      if: failure()
      runs-on: ubuntu-latest
      steps:
        - name: Report Failure
          run: echo "One of the previous jobs has failed."